[project]
name = "frontend"
version = "0.1.0"
description = "Default template for PDM package"
authors = [
    {name = "wold9168", email = "moewold@outlook.com"},
]
dependencies = [
    "flask>=3.1.2",
    "requests==2.31.0",
]
requires-python = "==3.13.*"
readme = "README.md"
license = {text = "MIT"}


[tool.pdm]
distribution = false
